### ISSUE TITLE
lime cpp target?

### ISSUE THREAD

**Issue by Ohmnivore** [luboslenco/haxebullet#2]
For web it's nice and cozy (in project.xml): `<dependency if="web" path="dependencies/ammo.js" />`

For cpp on the other hand, I just couldn't find any info about adding header/source files. I suppose I would have to inject it into the hxcpp build process somehow but I have no clue how that can be done.

**Comment by luboslenco** [comment]
Hey Ohmnivore,

I just found this topic, which talks about including this library(handy coincidence):
http://community.openfl.org/t/how-can-i-include-a-c-library-directory-to-hxcpp-build-process/1692/10

Is this helpful? There are some hxcpp tips included, will have to take a look too :)

**Comment by Ohmnivore** [comment]
I found it too, read it top to bottom but didn't understand anything xD. I'll try again tomorrow.
The @:buildXml tag looks interesting though.

**Comment by luboslenco** [comment]
Ah, should have thought so. I have no experience on this front since Kha handles it behind the scenes. Let me know if you figure it out, worst case we can try posting into that topic.

**Comment by Ohmnivore** [comment]
If I understand correctly the original poster ended up compiling the bullet sources as a dll and used them for linking. That still leaves me wondering how he included the header files in the preprocessor though.

I also looked at how koremake handles things and from what i've seen it includes the .cpp and .h files directly in the build process - much better than linking against a library imo. If it's possible in lime it would be the bee's knees.

I'll ask over there for sure.

**Comment by Ohmnivore** [comment]
I made a test with BtDiscreteDynamicsWorld, added the following right above its class definition. The header files are included, and the cpp stuff is compiled too. However for it to work we would have to add the same lines for every other class.

We could do it manually or I could attempt to make a build-time macro that would add these lines automatically from the existent @:include("BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h") tags.

Also does that break the koremake build process? It would be like adding everything in duplicate for a koremake build, so maybe it makes sense to add the @:buildXml stuff only if (for example) -DincludeBuildXml is defined.

```
@:buildXml("
	<files id='haxe'>
		<compilerflag value='-I${haxelib:haxebullet}/../cpp/bullet/'/>
		<file name='${haxelib:haxebullet}/../cpp/bullet/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.cpp'/>
	</files>
	<files id='__lib__'>
		<compilerflag value='-I${haxelib:haxebullet}/../cpp/bullet/'/>
		<file name='${haxelib:haxebullet}/../cpp/bullet/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.cpp'/>
	</files>
")
@:include("BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h")
@:keep
```

**Comment by Ohmnivore** [comment]
Done! https://gist.github.com/Ohmnivore/61897b4fc46170437776

I know a way (with lime.tools.PathHelper.getHaxelib) to make it so that lime automatically finds the sources in haxebullet's haxelib folder, but that would be terribly inconvenient for the snowkit folks :s

**Comment by luboslenco** [comment]
Closing down, also linked this issue to the readme as others may find it helpful.
