### ISSUE TITLE
Managing pointers in cpp target

### ISSUE THREAD

**Issue by Ohmnivore** [luboslenco/haxebullet#3]
At the moment my code looks something like this
```
class BGame extends BGroup {
	#if cpp
	public var world:Pointer<BtDiscreteDynamicsWorld>;
	#else
	public var world:BtDiscreteDynamicsWorld;
	#end
}
```

Luckily .value() works equivalently in js and cpp targets, but I still feel like these conditionals are annoying. I also suppose ammo.js has automatic garbage collection, but in cpp we need to call pointer.destroy(), right?

I think those are the only two things keeping the js and cpp versions not fully unified.

**Comment by Ohmnivore** [comment]
At this point I'm thinking either hxcpp manages pointers automatically, or if it doesn't maybe this will help: http://api.haxe.org/cpp/vm/Gc.html#setFinalizer

**Comment by Ohmnivore** [comment]
There's maybe other ways to do this, but this is the most obvious one to me:
```
#if js
typedef BTDiscreteDynamicsWorld = BtDiscreteDynamicsWorld;
#elseif cpp
typedef BTDiscreteDynamicsWorld = Pointer<BtDiscreteDynamicsWorld>;
#end
```
JS's create() and CPP's create() would both return a BTDiscreteDynamicsWorld, and in the user's classes fields would be defined as BTDiscreteDynamicsWorld too. Unless I'm overlooking something this would allow us to treat instances exactly the same in both targets, granted we're calling .value() first.

BTDiscreteDynamicsWorld instead of BtDiscreteDynamicsWorld is just an example, we would need a much more different typedef naming scheme to avoid confusion.

**Comment by Ohmnivore** [comment]
Even better:

```
typedef BulletDiscreteDynamicsWorld = 
#if js
BtDiscreteDynamicsWorld;
#elseif cpp
Pointer<BtDiscreteDynamicsWorld>;
#end
```

**Comment by Ohmnivore** [comment]
Betterer?

```
typedef BulletDiscreteDynamicsWorld = 
#if cpp
Pointer<
#end
BtDiscreteDynamicsWorld
#if cpp
>
#end
;
```

**Comment by Ohmnivore** [comment]
Hmm only way that stays fully compatible with FlashDevelop's autocomplete is

```
#if cpp
typedef BulletDiscreteDynamicsWorld = Pointer<BtDiscreteDynamicsWorld>;
#end
#if js
typedef BulletDiscreteDynamicsWorld = BtDiscreteDynamicsWorld;
#end
```

**Comment by Ohmnivore** [comment]
`for (i in 0...9000) {ctrlc();ctrlv();};`

Done! https://gist.github.com/Ohmnivore/081488802e5696746391

**Comment by luboslenco** [comment]
Hey,

Is it not the same like the thing already included?
https://github.com/luboslenco/haxebullet/blob/master/Sources/haxebullet/Bullet.hx#L1351

I went with 'Pointer' indication but it is easy to use your own typedefs as you do.

Ammo.js used to require calling destroy() too, but not sure if that is still the case. Ideally we get rid of that if possible:)

**Comment by Ohmnivore** [comment]
Oops. Didn't realize you had typedefs already.

I honestly have no idea what the .destroy() usage should be on cpp/js, i guess i'll figure it out when i find memory leaks.

**Comment by luboslenco** [comment]
Cleaning up, if someone needs to take care of .destroy() usage urgently feel free to open another issue.
